### ISSUE TITLE
The example in the doc doesn't work

### ISSUE THREAD

**Issue by Skywalker13** [chrisdickinson/clone-packages#8]
In the doc:

```javascript
clone.all('jsl@1.1.0', 'http://registry.npmjs.org/', 'http://my.reg/', function(err) {

})
```

But it's wrong, because the first argument must be the *clone* itself.
the 5th argument must be the credentials
the 6th argument must be *xform* ???
and then the callback

In the sources:

index.js
```javascript
module.exports.all = inner.cloneAll
```

clone-all.js
```javascript
function cloneAll(clone, pkg, src, dst, credentials, xform, ready) {
  return clone(
      pkg
    , src
    , dst
    , credentials
    , recursive(clone, src, dst, credentials)
    , ready
  )
}
```

Then I've tried with something like:
```javascript
var def = {
    name: npmPackage,
    version: deps[npmPackage]
};
clone.all(clone, def, from, dest, null, null, function (err) {
    callback (err);
});
```

It's works better but it enters in an infinite loop... I've not investigate but I think that is a problem of circular dep. When it "hangs", the node process leaks memory. .. it should be reported in an other issue ...

Regards

**Comment by hayes** [comment]
updated api and docs to match
